test:
	go test -timeout 30s -run ^Test ./...
	go test -timeout 30s -run ^Test ./contrib/pb/...
	go test -timeout 30s -run ^Test ./contrib/yaml/...

bench:
	go test -benchmem -run=^$$ -bench . github.com/lxzan/hasaki

cover:
	go test -coverprofile=bin/cover.out --cover ./...
	go test -coverprofile=bin/pb.out --cover ./contrib/pb/...
	go test -coverprofile=bin/yaml.out --cover ./contrib/yaml/...

install:
	go mod tidy
	go generate ./contrib/pb/codec.go
	go generate ./contrib/yaml/codec.go
